#define BLYNK_PRINT Serial
#define BLYNK_TEMPLATE_ID "PASTE YOUR TEMPLATE ID"
#define BLYNK_TEMPLATE_NAME "PASTE YOUR TEMPLATE NAME"
#define BLYNK_AUTH_TOKEN "PASTE YOUR BLYNK AUTHENTICATION TOKEN"
#define BLYNK_CUSTOM_HOST_NAME "your.custom.hostname"
#define BLYNK_CUSTOM_PORT "YOUR PORT NUMBER"

#define MANUAL_SSID "SSID Name"
#define MANUAL_PASSWORD "wifi password"
#define ACCESS_POINT_NAME "AP Name"
#define ACCESS_POINT_PASSWORD "AP Password"