# Script source: https://gist.github.com/marcovannoord/4275a25639427e13d6e74f17636bbd5f
# Big thanks to Marco van Noord for the script!

# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Initilize and update submodules
      run: |
        git submodule add https://github.com/sblantipodi/platformio_version_increment.git platformio_version_increment
        git submodule init
        git submodule update --init --recursive
    - name: List project directory
      run: ls -la
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    # It is important to first install the libraries before compiling, since otherwise compilation might fail to find the just-installed libraries
    - name: Install platformIO libraries
      run: pio lib install
    - name: Run PlatformIO
      run: platformio run